name: Compile JAR & Javadocs

on:
  push:
    branches:
      - master

jobs:
  compile:
    name: Compile JAR & Javadocs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '8'
          java-package: jdk
          architecture: x64
      - run: |
          cd src
          javadoc *.java -private -d ../docs
          javac *.java
          jar cfm ../StackTraceVisualizer.jar manifest.mf *.class
      - uses: EndBug/add-and-commit@v4
        with:
          ref: 'gh-pages'
          force: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}