name: Compile JAR & Javadocs

on: 
  release:
    types:
      - published
      - edited

jobs:
  compile:
    name: Compile JAR & Javadocs
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository 
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: true
      - name: Clone all branches
        run: |
          git fetch --prune --tags
          git checkout meta
          git checkout master
      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: '8'
          java-package: jdk
          architecture: x64
      - name: Configure GitHub credentials
        uses: oleksiyrudenko/gha-git-credentials@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Copy files to gh-pages branch
        run: |
          cd src
          javadoc *.java -private -d ../docs
          javac *.java
          jar cfm ../StackTraceVisualizer.jar manifest.mf *.class
          git merge meta --no-commit --no-ff -X theirs --allow-unrelated-histories
          git reset master
          cd ..
          zip -r StackTraceVisualizer.zip ./ -x '*.git*'
      - name: Upload zip to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: StackTraceVisualizer.zip
          asset_name: StackTraceVisualizer.zip
          tag: ${{ github.ref }}
          overwrite: true
      - name: Upload jar to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: StackTraceVisualizer.jar
          asset_name: StackTraceVisualizer.jar
          tag: ${{ github.ref }}
          overwrite: true
      - name: Push to GitHub
        uses: EndBug/add-and-commit@v4
        with:
          ref: 'gh-pages'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}